import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import fs from 'fs-extra'; 

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins],
  format: 'cjs',
  target: 'es2020',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  platform: 'browser', // Explicitly set platform to browser
  define: {
    'process.env.NODE_ENV': prod ? '"production"' : '"development"',
    'global': 'window', // Map global to window for browser environment
  },
  plugins: [
    // { // Плагін для копіювання теки assets
    //   name: 'copy-assets',
    //   setup(build) {
    //     build.onEnd(async result => {
    //       if (result.errors.length === 0) {
    //         try {
    //           await fs.copy('assets', 'assets', { overwrite: true });
    //           console.log('Assets copied successfully!');
    //         } catch (err) {
    //           console.error('Error copying assets:', err);
    //         }
    //       }
    //     });
    //   },
    // },
  ]
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}